theme ="bogster"
[editor]
line-number = "relative"
mouse = true
auto-completion = true
auto-info=true
idle-timeout=80
scrolloff = 5
[editor.cursor-shape]
insert = "bar"
normal = "block"
# select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
J = { K = "normal_mode" } # Maps `jk` to exit insert mode
[keys.normal]
[editor.lsp]
display-messages = true

